//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int ID { get; set; }
        public string Details { get; set; }
        public Nullable<int> Action { get; set; }
        public Nullable<int> RelatedID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
