//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutStanding
    {
        public int ID { get; set; }
        public int OsNumber { get; set; }
        public System.DateTime OsDate { get; set; }
        public double Amount { get; set; }
        public int StatusID { get; set; }
        public int JournalMovementID { get; set; }
    }
}
