//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMappingAccount
    {
        public int ID { get; set; }
        public Nullable<int> DebitCredit { get; set; }
        public Nullable<int> SalesCost { get; set; }
        public Nullable<int> SalesTypeID { get; set; }
        public Nullable<int> AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Lookup Lookup { get; set; }
    }
}
