//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesHistory()
        {
            this.SalesHistory1 = new HashSet<SalesHistory>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string TicketNumber { get; set; }
        public string CardNumber { get; set; }
        public string PaxName { get; set; }
        public string Remarks { get; set; }
        public string Destination { get; set; }
        public string PNR { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public Nullable<double> Fare { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<double> SalesAmount { get; set; }
        public Nullable<double> Profit { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<double> Visa { get; set; }
        public Nullable<double> Advance { get; set; }
        public Nullable<double> Card { get; set; }
        public Nullable<double> Complementary { get; set; }
        public Nullable<double> Commision { get; set; }
        public Nullable<long> DKNumber { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public string RefRemarks { get; set; }
        public string RefDescription { get; set; }
        public Nullable<int> SalesTypeID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public Nullable<int> AirlineID { get; set; }
        public Nullable<int> CreatedStaffID { get; set; }
        public Nullable<int> AccountantStaffID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> SalesStatusID { get; set; }
        public Nullable<int> ApproveStatusID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> SubAccountID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> HistoryCreatedStaffID { get; set; }
        public Nullable<int> RecievableMainAccountID { get; set; }
        public Nullable<int> CreditAccountID { get; set; }
        public Nullable<int> BankAccountID { get; set; }
        public Nullable<int> InvoiceNumberPNR { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Airline Airline { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual Lookup Lookup1 { get; set; }
        public virtual Lookup Lookup2 { get; set; }
        public virtual Lookup Lookup3 { get; set; }
        public virtual Sale Sale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesHistory> SalesHistory1 { get; set; }
        public virtual SalesHistory SalesHistory2 { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
